[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:KasparRosin/nvim-config.git"
    refreshPeriod = "168h"

[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".nvm"]
    type = "archive"
    url = "https://github.com/nvm-sh/nvm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
