#!/usr/bin/env zsh

sudo apt install stow
exit 0
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="git,zsh,ubuntuos,nvim,i3"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
